nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']  # Vous pouvez restreindre à des origines spécifiques
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['POST', 'GET', 'DELETE', 'PUT', 'OPTIONS']
        expose_headers: []
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['*']  # Vous pouvez restreindre à des origines spécifiques
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'GET', 'DELETE', 'PUT', 'OPTIONS']
            max_age: 3600
