version: '3.8'  # Utilisez la version 3.8 pour les dernières fonctionnalités
services:
  mysql:
    image: "mysql:5.7"
    container_name: mysql
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql  # Volume persistant pour les données MySQL
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_USER=root
      - MYSQL_DATABASE=wordpress
    ports:
      - "3306:3306"
    expose:
      - 3306

  my_super_app:
    build: ./my_super_app
    image: "my_super_app:latest"
    container_name: my_super_app
    depends_on:
      - mysql
    command: sh -c "/wait && /sayhello"
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    volumes:
      - ./env_data:/app/.env  # Volume pour persister le fichier .env
    ports:
      - "8000:8000"  # Si l'application expose un port, ajustez selon vos besoins

volumes:
  mysql_data:
    driver: local  # Volume persistant pour la base de données
  env_data:
    driver: local  # Volume pour sauvegarder le fichier .env
